module.exports = {
  MAX_SRAI_DEPTH: 200,
  MAX_LOOP_COUNT: 99,
  ENABLE_NETWORK_CONNECTION: true,
  ENABLE_JAVASCRIPT: true,
  MAX_JS_TIMEOUT: 200,
  ENABLE_SYSTEM: true,
  MAX_SYSTEM_TIMEOUT: 200,
  name: 'AIML2.js',
  version: '0.1',
}
